worker_processes auto;

events {
	worker_connections 1024;
}

http {
	include       /etc/nginx/mime.types;
	# default_type  application/octet-stream;

	upstream wordpress {
		server wordpress:9000;
	}

	server {
		listen 443 ssl;
		ssl_certificate /etc/nginx/certs/inception.crt;
		ssl_certificate_key /etc/nginx/certs/inception.key;
		absolute_redirect off;
		keepalive_timeout   70;
		ssl_session_cache   shared:SSL:10m;
		ssl_protocols       TLSv1.2 TLSv1.3;
		server_name hbourlot.42.fr;
		root /var/www/html;
		index index.php;

		# location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$ {
		# 	try_files $uri =404;
		# 	expires 7d;
		# 	access_log off;
		# }

		location ~ \.php$ {
			# try_files $uri =404;
			fastcgi_pass wordpress;
			fastcgi_index index.php;
			include fastcgi_params;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			# fastcgi_param SCRIPT_NAME $fastcgi_script_name;
		}

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		error_page   500 502 503 504  /50x.html;
		location = /50x.html {
			root   /usr/share/nginx/html;
		}
	}
}
