services:
    mariadb:
        secrets:
            - db_password
            - db_root_password
        container_name: mariadb
        image: mariadb:${MARIADB_IMAGE_TAG}
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        restart: always
        networks:
            - inception
        volumes:
            - mariadb:/var/lib/mysql
        env_file:
            - .env

    wordpress:
        secrets:
            - db_password
            - credentials
        container_name: wordpress
        depends_on:
            - mariadb
        image: wordpress:${WORDPRESS_IMAGE_TAG}
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env
        environment:
            - WORDPRESS_DB_HOST=mariadb:${DB_PORT}
            - WORDPRESS_DB_USER=${MYSQL_USER}
            - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception

    nginx:
        container_name: nginx
        restart: always
        depends_on:
            - wordpress
        image: nginx:${NGINX_IMAGE_TAG}
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception
# Volumes conf
volumes:
    mariadb:
        driver: local
        driver_opts:
            type: none
            device: ${DB_DATA_PATH}
            o: bind
    wordpress:
        driver: local
        driver_opts:
            type: none
            device: ${WP_DATA_PATH}
            o: bind

networks:
    inception:
        driver: bridge # or host, none, overlay, macvlan

secrets:
    db_password:
        file: ../secrets/db_password.txt
    db_root_password:
        file: ../secrets/db_root_password.txt
    credentials:
        file: ../secrets/credentials.txt
