services:
    mariadb:
        secrets:
            - db_password
            - db_root_password
        container_name: mariadb
        image: mariadb
        build:
            context: requirements/mariadb
            dockerfile: mariadb.Dockerfile
        restart: always
        networks:
            - inception
        volumes:
            - mariadb:/var/lib/mysql
        env_file:
            - .env

    wordpress:
        secrets:
            - db_password
        container_name: wordpress
        depends_on:
            - mariadb
        image: wordpress
        build:
            context: requirements/wordpress
            dockerfile: wordpress.Dockerfile
        restart: always
        env_file:
            - .env
        environment:
            - WORDPRESS_DB_HOST=mariadb:3306
            - WORDPRESS_DB_USER=${MYSQL_USER}
            - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password
            - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception

    nginx:
        container_name: nginx
        restart: always
        depends_on:
            - wordpress
        image: nginx
        build:
            context: requirements/nginx
            dockerfile: nginx.Dockerfile
        ports:
            - "8080:443"
        volumes:
            - wordpress:/var/www/html
            - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - inception
# Volumes conf
volumes:
    mariadb:
        driver: local
        driver_opts:
            type: none
            device: /Users/hugobourlot/data/mariadb
            o: bind
    wordpress:
        driver: local
        driver_opts:
            type: none
            device: /Users/hugobourlot/data/wordpress
            o: bind

networks:
    inception:
        driver: bridge # or host, none, overlay, macvlan

secrets:
    db_password:
        file: ../secrets/db_password.txt
    db_root_password:
        file: ../secrets/db_root_password.txt
